name: hrms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  geolocator: ^14.0.2
  intl: ^0.20.2
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# 🚀 রুট লেভেল আইকন কনফিগারেশন (ভুল কোডগুলো রিমুভ করে ক্লিন করা হয়েছে)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/hrm.png"

flutter:
  uses-material-design: true

  # 🚀 আইকন অ্যাসেট পাথটি এখানে সচল করে দেওয়া হলো যাতে ফ্ল্যাটার এটি রিড করতে পারে
  assets:
    - assets/icon/hrm.png